kind: Deployment
apiVersion: apps/v1
metadata:
  name: reacttodo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: reacttodo
  template:
    metadata:
      labels:
        app: reacttodo
    spec:
      containers:
        - name: reacttodo
          image: sujithkumar597/reacttodo:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: reacttodo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31113
  selector:
    app: reacttodo